/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package greenpanda;

/**
 *
 * @author User
 */
public class Money extends javax.swing.JFrame {

    /**
     * Creates new form Money
     */
    public Money() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        hundredtaka = new javax.swing.JLabel();
        fiftytaka = new javax.swing.JLabel();
        twintytaka = new javax.swing.JLabel();
        tentaka = new javax.swing.JLabel();
        fivetaka = new javax.swing.JLabel();
        twotaka = new javax.swing.JLabel();
        onetaka = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jTextField9.setText("jTextField9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(715, 488));

        jPanel1.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/greenpanda/show2.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(490, 310, 160, 70);

        hundredtaka.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        hundredtaka.setForeground(new java.awt.Color(0, 102, 0));
        hundredtaka.setText("0");
        jPanel1.add(hundredtaka);
        hundredtaka.setBounds(650, 230, 40, 20);

        fiftytaka.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        fiftytaka.setForeground(new java.awt.Color(0, 102, 0));
        fiftytaka.setText("0");
        jPanel1.add(fiftytaka);
        fiftytaka.setBounds(560, 230, 30, 30);

        twintytaka.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        twintytaka.setForeground(new java.awt.Color(0, 102, 0));
        twintytaka.setText("0");
        jPanel1.add(twintytaka);
        twintytaka.setBounds(470, 230, 30, 30);

        tentaka.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        tentaka.setForeground(new java.awt.Color(0, 102, 0));
        tentaka.setText("0");
        jPanel1.add(tentaka);
        tentaka.setBounds(370, 230, 30, 30);

        fivetaka.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        fivetaka.setForeground(new java.awt.Color(0, 102, 0));
        fivetaka.setText("0");
        jPanel1.add(fivetaka);
        fivetaka.setBounds(280, 230, 30, 30);

        twotaka.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        twotaka.setForeground(new java.awt.Color(0, 102, 0));
        twotaka.setText("0");
        jPanel1.add(twotaka);
        twotaka.setBounds(170, 230, 20, 20);

        onetaka.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        onetaka.setForeground(new java.awt.Color(0, 102, 0));
        onetaka.setText("0");
        jPanel1.add(onetaka);
        onetaka.setBounds(50, 230, 30, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/greenpanda/moneylist.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 0, 700, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        int price = Info.price;
        System.out.println(price);
        int payment = Info.payment;
        System.out.println(payment);
        int ret = payment - price;
        System.out.println(ret);
        
        int temp = ret / 100;
        String taka = String.valueOf(temp);
        hundredtaka.setText(taka);
        ret = ret % 100;
        
        temp = ret / 50;
        taka = String.valueOf(temp);
        fiftytaka.setText(taka);
        ret = ret % 50;
        
        temp = ret / 20;
        taka = String.valueOf(temp);
        twintytaka.setText(taka);
        ret = ret % 20;
        
        temp = ret / 10;
        taka = String.valueOf(temp);
        tentaka.setText(taka);
        ret = ret % 10;
        
        temp = ret / 5;
        taka = String.valueOf(temp);
        fivetaka.setText(taka);
        ret = ret % 5;
        
        temp = ret / 2;
        taka = String.valueOf(temp);
        twotaka.setText(taka);
        ret = ret % 2;
        
        temp = ret / 1;
        taka = String.valueOf(temp);
        onetaka.setText(taka);
       
        
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Money().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fiftytaka;
    private javax.swing.JLabel fivetaka;
    private javax.swing.JLabel hundredtaka;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel onetaka;
    private javax.swing.JLabel tentaka;
    private javax.swing.JLabel twintytaka;
    private javax.swing.JLabel twotaka;
    // End of variables declaration//GEN-END:variables
}
